### ISSUE TITLE
FIP Proposal: Alter sector upgrade behavour to make an upgraded sector's power consistent with a newly sealed sector

### ISSUE THREAD

**Issue by neondragon** [filecoin-project/FIPs#93] opened 2021-04-05 20:11 UTC
# FIP Proposal: Alter sector upgrade behavour to make an upgraded sector's power consistent with a newly sealed sector

## Author

Alex Fox - Neonix

Slack: @NeonixAF f019551

## Overview

The Filecoin Spec describes the purpose of the sector upgrade mechanism in 2.6.1.1 Sector Lifecycle:

    It is reasonable to assume that miners enter the network by adding Committed Capacity sectors, that is, sectors that do not contain user data. Once miners agree storage deals with clients, they upgrade their sectors to Regular Sectors. Alternatively, if they find Verified Clients and agree a storage deal with them, they upgrade their sector accordingly. Depending on whether or not a sector includes a (verified) deal, the miner acquires the corresponding storage power in the network.

(https://spec.filecoin.io/#section-systems.filecoin_mining.sector.lifecycle)

And in 2.6.1.6 Upgrading Sectors:

    In order for a Miner to maximize storage power (and profit), they should take advantage of all available storage space immediately, even before they find enough Clients to use this space.

    [...]

    If the newly ProveCommitted Regular sector contains a Verified Client deal, i.e., a deal with higher Sector Quality, then the miner’s storage power will increase accordingly.

(https://spec.filecoin.io/#section-systems.filecoin_mining.sector.adding_storage)

The intention seems clear that miners should always pledge capacity when they have the resources to do so, and there is no indication that performing a sector upgrade should be discouraged in any circumstance.

## Problem

There is a situation where upgrading a sector will disadvantage a miner. When upgrading a sector with a deal having a duration shorter than the lifetime of the old sector, the new sector is given the same Expiration epoch as the sector that it replaces. Due to the calculation of the Sector Quality Multiplier, the new sector has a lower storage power than a sector which had been sealed without upgrading.

For example:
1. A miner marks a sector for upgrade. The sector's expiration epoch is 1 year from now.
2. The miner receives a 32GiB verified deal, with a duration of 6 months. The deal is sealed into a sector, and the new sector replaces the sector marked for upgrade. The new sector inherits the old sector's expiration epoch of 1 year from now.
3. The Sector Quality Multiplier of this new sector is half of what it would have been if the sector had been sealed without upgrading. This results in the upgraded sector having half of the power that a normal sector would have had, but for twice the amount of time.

Even though the upgraded sector has the same total amount of power overall, the miner receives less benefit from this power because half of it has been pushed into the future when the network will presumably have grown and the reward received for that power will be smaller.

This could result in a miner being unfairly penalised after having pledged storage space to the network when they unexpectedly receive many short deals. Or it could provide a peverse incentive for a miner to not pledge space to the network if they expect to receive significant short verified deals, as they will make the rational decision to avoid this penalty.

## Proposal

The calculation of Sector Quality should be changed for sectors that are upgrading CC sectors.

For the purposes of the Sector Quality calculation, the sector should be treated as if its expiration is the epoch on which the longest deal in the sector expires. As such, the miner receives the same benefit from Verified Deal Weight, at the same time, as they would have had they sealed the sector without upgrading.

After the last deal in the sector expires, it reverts back to having a Sector Quality of a CC sector, and power reduces accordingly.

Additionally, as the sector's power has reverted back to that of a CC sector, the whole sector has essentially reverted back to being a CC sector, and as such it may make sense to permit upgrading it again subject to maximum allowed sector lifetime.

**Comment by neondragon** [comment] 2021-04-06 13:09
To be clear, what I am intending to enable is the following lifecycle:
* A miner pledges a CC sector to the network.
* The miner decides to upgrade the CC sector with deal(s).
* The upgraded sector is allowed a 'downgrade epoch' on, or after the epoch on which the longest deal in the sector expires.
* The sector is treated as two parts, the upgraded portion, and the downgraded portion.
* The collateral requirement, DealWeight, and VerifiedPower of the upgraded portion is calculated as if it were a newly sealed sector that expires on the downgrade epoch.
* On the downgrade epoch, excess collateral is returned from the sector to the miner available balance, and the sector's collateral along with its power returns to that of a CC sector.
* The downgraded sector becomes eligible to be upgraded again (to make full use of available pledged space)
* The downgraded sector's expiration date is the same as the originally pledged CC sector

An upgraded and a downgraded sector minimally retain the expiration epoch of the originally pledged sector so that there is no mechanism to receive a CC sector's collateral back early.

I believe allowing an upgraded sector the opportunity to provide the same storage power for the same duration as a newly sealed sector ensures that miners will not need to consider this potential disadvantage and can more confidently pledge capacity knowing it can be made full use of.

As the network has locked the CC (or downgraded) sector's pledge collateral, and mandates that it be proved for its full remaining lifespan, I believe this improvement would also allow more effective use of this available resource by ensuring that sectors without active deals are always eligible to be (re)upgraded to contain deals.

**Comment by arajasek** [comment] 2021-04-07 19:27
I don’t fully understand the nuance here, but this miiight make a lot of sense? @zixuanzh @ZenGround0 can either of you weigh in?

**Comment by ZenGround0** [comment] 2021-04-07 23:07
The problem is clear and I would like to see it solved.

The proposed solution looks pretty good. Prove committing a cc sector could schedule a cron event to handle processing the downgrade epoch. In terms of mechanism design I think this is strictly better for sector quality estimation.  But then scaling might be a bit tricky. Downgrading is similar to termination in that it needs access to sector infos, unlike on-time expiration, so it should be handled similarly.  Proposal along these lines: make downgrading a user initiated action that can only succeed once the downgrade epoch has passed.

Assuming no scaling issues it is unambiguously good for the system to have more accurate power estimations. It is less clear if the proposed adjustments of pledge are in line with the desired mechanism design.  It is unclear to me if IPBase term should be reduced with a corresponding drop in power.  @zixuanzh is the expert here and can speak to that.  One complication unaddressed is the potential for circulating supply and hence LockTarget term to go up after the downgrade epoch making the new IP greater.  But with a user initiated downgrade it's easy to expect the incoming balance to carry enough balance to cover pledge changes and abort in the case of insufficient funds.

**Comment by ribasushi** [comment] 2021-04-08 19:48
I think doing this will open an abuse avenue, where folks who originally did a bunch of 540 day CC, can have a change-of-heart at month 1 out of the 18 months, create a number of self-dealt 6 month sectors, replace the existing CC with them, and have an exit at month 7, instead of what they originally pledged to the network

@zixuanzh and @nicola would have to chime in whether this is an actual concern or not (creating these new 6-month sectors is not free, so maybe the incentive simply isn't there...)

**Comment by nicola** [comment] 2021-04-08 21:54
I will look into this, thank you for taking the time writing this concern.

While I think what you are pointing out is important, it may be still not rational to upgrade using the current protocol..

My overall goal with a future protocol upgrade is to try to solve the issue at the root: support sector updates without resealing.

**Comment by kaitlin-beegle** [comment] 2021-08-16 21:52
Hey @nicola! It's been some time, but it seems like this concern would still be relevant.  Did you ever have a chance to look into this proposal? 

Also tagging @zixuanzh again since there appear to be some concerns related to incentive design.

**Comment by kaitlin-beegle** [comment] 2021-12-15 00:02
This is being closed; the primary issue context will be addressed in the upcoming Snap Deals enhancement.

**Closed by kaitlin-beegle** 2021-12-15 00:02 UTC
Labels: Technical - Implementation, New Idea, Community Input Needed, PreFIP, Active
